/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Module;

import com.sbix.jnotify.NPosition;
import com.sbix.jnotify.NoticeWindow;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Jayjomjohn
 */
public class Login extends javax.swing.JFrame {

    int ctr = 0;
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
     public static int empId;
     
    public Login() {
        initComponents();
        conn=JavaConnector.ConnecrDb();
        this.setLocationRelativeTo(null);
        this.setOpacity(0.8f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        SignUpPanel = new javax.swing.JPanel();
        SignUpLabel = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        LoginLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 83, 155), 6, true));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(58, 83, 155));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconB/icons8_Admin_100px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 121));

        txtUser.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setText("Username");
        txtUser.setBorder(null);
        txtUser.setOpaque(false);
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 143, 176, 33));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 187, 99, 44));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 176, 176, 11));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 143, 99, 44));

        txtPass.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(null);
        txtPass.setOpaque(false);
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 187, 176, 33));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 220, 176, 11));

        SignUpPanel.setBackground(new java.awt.Color(0, 0, 0));
        SignUpPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        SignUpPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpPanelMouseExited(evt);
            }
        });
        SignUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUpLabel.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SignUpLabel.setForeground(new java.awt.Color(255, 102, 0));
        SignUpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUpLabel.setText("Cancel");
        SignUpPanel.add(SignUpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 99, 55));

        jPanel1.add(SignUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 242, 99, 55));

        LoginPanel.setBackground(new java.awt.Color(0, 0, 0));
        LoginPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        LoginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginPanelMouseExited(evt);
            }
        });
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginLabel.setBackground(new java.awt.Color(0, 0, 0));
        LoginLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(255, 102, 0));
        LoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginLabel.setText("Login");
        LoginPanel.add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 99, 55));

        jPanel1.add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 242, 99, 55));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sign-Up");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 308, 220, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpPanelMouseClicked
      System.exit(0);
    }//GEN-LAST:event_SignUpPanelMouseClicked

    private void SignUpPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpPanelMouseEntered
       SignUpLabel.setForeground(Color.WHITE);
       SignUpPanel.setBackground(new Color(255,102,0));
       SignUpPanel.setBorder(new LineBorder(new Color(255,102,0),1,true));
    }//GEN-LAST:event_SignUpPanelMouseEntered

    private void SignUpPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpPanelMouseExited
       SignUpLabel.setForeground(new Color(255,102,0));
       SignUpPanel.setBackground(Color.BLACK);
       SignUpPanel.setBorder(new LineBorder(Color.WHITE, 1,true));
    }//GEN-LAST:event_SignUpPanelMouseExited

    private void LoginPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPanelMouseEntered
       LoginLabel.setForeground(Color.WHITE);
       LoginPanel.setBackground(new Color(255,102,0));
       LoginPanel.setBorder(new LineBorder(new Color(255,102,0),1,true));
    }//GEN-LAST:event_LoginPanelMouseEntered

    private void LoginPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPanelMouseExited
       LoginLabel.setForeground(new Color(255,102,0));
       LoginPanel.setBackground(Color.BLACK);
       LoginPanel.setBorder(new LineBorder(Color.WHITE, 1,true));
    }//GEN-LAST:event_LoginPanelMouseExited
int xx,xy;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
         xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
       if(txtUser.getText().equals("Username")){
          txtUser.setText("");
      }
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
          if(txtUser.getText().equals("")){
        txtUser.setText("Username");
        }
    }//GEN-LAST:event_txtUserFocusLost

    private void LoginPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPanelMouseClicked
     
        
    try {
        pst=conn.prepareStatement("SELECT username, password, picture FROM tbllogin WHERE username=? AND password=?");
        pst.setString(1,txtUser.getText());
        pst.setString(2,txtPass.getText());
        rs=pst.executeQuery();
       
       
        if(rs.next()) {
            
            MainHome m = new MainHome();
            m.setVisible(true);
            m.setExtendedState(MAXIMIZED_BOTH);
            m.pack();                   
            m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            //Show user profile pic in the top 
            m.labelmg.setIcon(new MyImage().resizePic(null, rs.getBytes("picture"), m.labelmg.getWidth(), m.labelmg.getHeight()));
            String a =rs.getString("username");
            m.labelLogin.setText("Logged in As: " + a +"!");
                    
            
            
            Date currentDate = GregorianCalendar.getInstance().getTime();
            DateFormat df = DateFormat.getDateInstance();
            String dateString = df.format(currentDate);

            Date d = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss:EEEE");
            String timeString = sdf.format(d);         

            String value0 = timeString;
            String value1 = dateString;                       
            
            try {
              String reg= "insert into tblaudit (login_name, date, status) "
                      + "values ('"+a+"','"+value0+" / "+value1+"','Logged in')";
                pst=conn.prepareStatement(reg);
                pst.execute();
                m.showaudit();
                m.countaudit();
                m.countuser();
                this.dispose();
                             
        }catch(Exception e) {
             
        }
        NoticeWindow n = new NoticeWindow(new Color(0,111,177),"\t\tLogin Successfully",NORMAL,NPosition.BOTTOM_RIGHT);
     
        }else{
            JOptionPane.showMessageDialog(null, "Access Denied!:\nInvalid Username or Password","Warning",JOptionPane.WARNING_MESSAGE);
            ctr += 1;
        }if(ctr == 3) {
                JOptionPane.showMessageDialog(null, "The Program is now closing ..");
                this.dispose();
            } 
        
       
        
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    
         
    }//GEN-LAST:event_LoginPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
            }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LoginLabel;
    public javax.swing.JPanel LoginPanel;
    public javax.swing.JLabel SignUpLabel;
    public javax.swing.JPanel SignUpPanel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JPasswordField txtPass;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
